/*
Copyright 2020 Replicated, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/replicatedhq/kubeflare/pkg/apis/crds/v1alpha1"
	scheme "github.com/replicatedhq/kubeflare/pkg/client/kubeflareclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// APITokensGetter has a method to return a APITokenInterface.
// A group's client should implement this interface.
type APITokensGetter interface {
	APITokens(namespace string) APITokenInterface
}

// APITokenInterface has methods to work with APIToken resources.
type APITokenInterface interface {
	Create(ctx context.Context, aPIToken *v1alpha1.APIToken, opts v1.CreateOptions) (*v1alpha1.APIToken, error)
	Update(ctx context.Context, aPIToken *v1alpha1.APIToken, opts v1.UpdateOptions) (*v1alpha1.APIToken, error)
	UpdateStatus(ctx context.Context, aPIToken *v1alpha1.APIToken, opts v1.UpdateOptions) (*v1alpha1.APIToken, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.APIToken, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.APITokenList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.APIToken, err error)
	APITokenExpansion
}

// aPITokens implements APITokenInterface
type aPITokens struct {
	client rest.Interface
	ns     string
}

// newAPITokens returns a APITokens
func newAPITokens(c *CrdsV1alpha1Client, namespace string) *aPITokens {
	return &aPITokens{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the aPIToken, and returns the corresponding aPIToken object, and an error if there is any.
func (c *aPITokens) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.APIToken, err error) {
	result = &v1alpha1.APIToken{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("apitokens").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of APITokens that match those selectors.
func (c *aPITokens) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.APITokenList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.APITokenList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("apitokens").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested aPITokens.
func (c *aPITokens) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("apitokens").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a aPIToken and creates it.  Returns the server's representation of the aPIToken, and an error, if there is any.
func (c *aPITokens) Create(ctx context.Context, aPIToken *v1alpha1.APIToken, opts v1.CreateOptions) (result *v1alpha1.APIToken, err error) {
	result = &v1alpha1.APIToken{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("apitokens").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aPIToken).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a aPIToken and updates it. Returns the server's representation of the aPIToken, and an error, if there is any.
func (c *aPITokens) Update(ctx context.Context, aPIToken *v1alpha1.APIToken, opts v1.UpdateOptions) (result *v1alpha1.APIToken, err error) {
	result = &v1alpha1.APIToken{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("apitokens").
		Name(aPIToken.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aPIToken).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *aPITokens) UpdateStatus(ctx context.Context, aPIToken *v1alpha1.APIToken, opts v1.UpdateOptions) (result *v1alpha1.APIToken, err error) {
	result = &v1alpha1.APIToken{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("apitokens").
		Name(aPIToken.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aPIToken).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the aPIToken and deletes it. Returns an error if one occurs.
func (c *aPITokens) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("apitokens").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *aPITokens) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("apitokens").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched aPIToken.
func (c *aPITokens) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.APIToken, err error) {
	result = &v1alpha1.APIToken{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("apitokens").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
