/*
Copyright 2020 Replicated, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/replicatedhq/kubeflare/pkg/apis/crds/v1alpha1"
	scheme "github.com/replicatedhq/kubeflare/pkg/client/kubeflareclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// WorkerRoutesGetter has a method to return a WorkerRouteInterface.
// A group's client should implement this interface.
type WorkerRoutesGetter interface {
	WorkerRoutes(namespace string) WorkerRouteInterface
}

// WorkerRouteInterface has methods to work with WorkerRoute resources.
type WorkerRouteInterface interface {
	Create(ctx context.Context, workerRoute *v1alpha1.WorkerRoute, opts v1.CreateOptions) (*v1alpha1.WorkerRoute, error)
	Update(ctx context.Context, workerRoute *v1alpha1.WorkerRoute, opts v1.UpdateOptions) (*v1alpha1.WorkerRoute, error)
	UpdateStatus(ctx context.Context, workerRoute *v1alpha1.WorkerRoute, opts v1.UpdateOptions) (*v1alpha1.WorkerRoute, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.WorkerRoute, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.WorkerRouteList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WorkerRoute, err error)
	WorkerRouteExpansion
}

// workerRoutes implements WorkerRouteInterface
type workerRoutes struct {
	client rest.Interface
	ns     string
}

// newWorkerRoutes returns a WorkerRoutes
func newWorkerRoutes(c *CrdsV1alpha1Client, namespace string) *workerRoutes {
	return &workerRoutes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the workerRoute, and returns the corresponding workerRoute object, and an error if there is any.
func (c *workerRoutes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WorkerRoute, err error) {
	result = &v1alpha1.WorkerRoute{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("workerroutes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of WorkerRoutes that match those selectors.
func (c *workerRoutes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WorkerRouteList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.WorkerRouteList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("workerroutes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested workerRoutes.
func (c *workerRoutes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("workerroutes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a workerRoute and creates it.  Returns the server's representation of the workerRoute, and an error, if there is any.
func (c *workerRoutes) Create(ctx context.Context, workerRoute *v1alpha1.WorkerRoute, opts v1.CreateOptions) (result *v1alpha1.WorkerRoute, err error) {
	result = &v1alpha1.WorkerRoute{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("workerroutes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(workerRoute).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a workerRoute and updates it. Returns the server's representation of the workerRoute, and an error, if there is any.
func (c *workerRoutes) Update(ctx context.Context, workerRoute *v1alpha1.WorkerRoute, opts v1.UpdateOptions) (result *v1alpha1.WorkerRoute, err error) {
	result = &v1alpha1.WorkerRoute{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("workerroutes").
		Name(workerRoute.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(workerRoute).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *workerRoutes) UpdateStatus(ctx context.Context, workerRoute *v1alpha1.WorkerRoute, opts v1.UpdateOptions) (result *v1alpha1.WorkerRoute, err error) {
	result = &v1alpha1.WorkerRoute{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("workerroutes").
		Name(workerRoute.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(workerRoute).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the workerRoute and deletes it. Returns an error if one occurs.
func (c *workerRoutes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("workerroutes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *workerRoutes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("workerroutes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched workerRoute.
func (c *workerRoutes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WorkerRoute, err error) {
	result = &v1alpha1.WorkerRoute{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("workerroutes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
