FROM ubuntu:latest

RUN apt-get update -y && apt-get install -y ca-certificates

WORKDIR /
COPY kubeflare /kubeflare
RUN chmod a+x /kubeflare

RUN useradd -c 'kubeflare-manager user' -m -d /home/kubeflare-manager -s /bin/bash -u 1001 kubeflare-manager
USER kubeflare-manager
ENV HOME /home/kubeflare-manager

ENTRYPOINT ["/kubeflare", "manager"]
