FROM ubuntu:latest

RUN apt-get update -y && apt-get install -y ca-certificates

WORKDIR /
COPY manager /manager
RUN chmod a+x /manager

RUN useradd -c 'kubeflare-manager user' -m -d /home/kubeflare-manager -s /bin/bash -u 1001 kubeflare-manager
USER kubeflare-manager
ENV HOME /home/kubeflare-manager

ENTRYPOINT ["/manager", "run"]
