/*
Copyright 2020 Replicated, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/replicatedhq/kubeflare/pkg/apis/crds/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWorkerRoutes implements WorkerRouteInterface
type FakeWorkerRoutes struct {
	Fake *FakeCrdsV1alpha1
	ns   string
}

var workerroutesResource = schema.GroupVersionResource{Group: "crds.kubeflare.io", Version: "v1alpha1", Resource: "workerroutes"}

var workerroutesKind = schema.GroupVersionKind{Group: "crds.kubeflare.io", Version: "v1alpha1", Kind: "WorkerRoute"}

// Get takes name of the workerRoute, and returns the corresponding workerRoute object, and an error if there is any.
func (c *FakeWorkerRoutes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WorkerRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(workerroutesResource, c.ns, name), &v1alpha1.WorkerRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkerRoute), err
}

// List takes label and field selectors, and returns the list of WorkerRoutes that match those selectors.
func (c *FakeWorkerRoutes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WorkerRouteList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(workerroutesResource, workerroutesKind, c.ns, opts), &v1alpha1.WorkerRouteList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WorkerRouteList{ListMeta: obj.(*v1alpha1.WorkerRouteList).ListMeta}
	for _, item := range obj.(*v1alpha1.WorkerRouteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested workerRoutes.
func (c *FakeWorkerRoutes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(workerroutesResource, c.ns, opts))

}

// Create takes the representation of a workerRoute and creates it.  Returns the server's representation of the workerRoute, and an error, if there is any.
func (c *FakeWorkerRoutes) Create(ctx context.Context, workerRoute *v1alpha1.WorkerRoute, opts v1.CreateOptions) (result *v1alpha1.WorkerRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(workerroutesResource, c.ns, workerRoute), &v1alpha1.WorkerRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkerRoute), err
}

// Update takes the representation of a workerRoute and updates it. Returns the server's representation of the workerRoute, and an error, if there is any.
func (c *FakeWorkerRoutes) Update(ctx context.Context, workerRoute *v1alpha1.WorkerRoute, opts v1.UpdateOptions) (result *v1alpha1.WorkerRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(workerroutesResource, c.ns, workerRoute), &v1alpha1.WorkerRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkerRoute), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWorkerRoutes) UpdateStatus(ctx context.Context, workerRoute *v1alpha1.WorkerRoute, opts v1.UpdateOptions) (*v1alpha1.WorkerRoute, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(workerroutesResource, "status", c.ns, workerRoute), &v1alpha1.WorkerRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkerRoute), err
}

// Delete takes name of the workerRoute and deletes it. Returns an error if one occurs.
func (c *FakeWorkerRoutes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(workerroutesResource, c.ns, name), &v1alpha1.WorkerRoute{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWorkerRoutes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(workerroutesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.WorkerRouteList{})
	return err
}

// Patch applies the patch and returns the patched workerRoute.
func (c *FakeWorkerRoutes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WorkerRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(workerroutesResource, c.ns, name, pt, data, subresources...), &v1alpha1.WorkerRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkerRoute), err
}
