/*
Copyright 2020 Replicated, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/replicatedhq/kubeflare/pkg/apis/crds/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAPITokens implements APITokenInterface
type FakeAPITokens struct {
	Fake *FakeCrdsV1alpha1
	ns   string
}

var apitokensResource = schema.GroupVersionResource{Group: "crds.kubeflare.io", Version: "v1alpha1", Resource: "apitokens"}

var apitokensKind = schema.GroupVersionKind{Group: "crds.kubeflare.io", Version: "v1alpha1", Kind: "APIToken"}

// Get takes name of the aPIToken, and returns the corresponding aPIToken object, and an error if there is any.
func (c *FakeAPITokens) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.APIToken, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(apitokensResource, c.ns, name), &v1alpha1.APIToken{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIToken), err
}

// List takes label and field selectors, and returns the list of APITokens that match those selectors.
func (c *FakeAPITokens) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.APITokenList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(apitokensResource, apitokensKind, c.ns, opts), &v1alpha1.APITokenList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.APITokenList{ListMeta: obj.(*v1alpha1.APITokenList).ListMeta}
	for _, item := range obj.(*v1alpha1.APITokenList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aPITokens.
func (c *FakeAPITokens) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(apitokensResource, c.ns, opts))

}

// Create takes the representation of a aPIToken and creates it.  Returns the server's representation of the aPIToken, and an error, if there is any.
func (c *FakeAPITokens) Create(ctx context.Context, aPIToken *v1alpha1.APIToken, opts v1.CreateOptions) (result *v1alpha1.APIToken, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(apitokensResource, c.ns, aPIToken), &v1alpha1.APIToken{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIToken), err
}

// Update takes the representation of a aPIToken and updates it. Returns the server's representation of the aPIToken, and an error, if there is any.
func (c *FakeAPITokens) Update(ctx context.Context, aPIToken *v1alpha1.APIToken, opts v1.UpdateOptions) (result *v1alpha1.APIToken, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(apitokensResource, c.ns, aPIToken), &v1alpha1.APIToken{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIToken), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAPITokens) UpdateStatus(ctx context.Context, aPIToken *v1alpha1.APIToken, opts v1.UpdateOptions) (*v1alpha1.APIToken, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(apitokensResource, "status", c.ns, aPIToken), &v1alpha1.APIToken{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIToken), err
}

// Delete takes name of the aPIToken and deletes it. Returns an error if one occurs.
func (c *FakeAPITokens) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(apitokensResource, c.ns, name), &v1alpha1.APIToken{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAPITokens) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(apitokensResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.APITokenList{})
	return err
}

// Patch applies the patch and returns the patched aPIToken.
func (c *FakeAPITokens) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.APIToken, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(apitokensResource, c.ns, name, pt, data, subresources...), &v1alpha1.APIToken{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIToken), err
}
