/*
Copyright 2020 Replicated, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/replicatedhq/kubeflare/pkg/apis/crds/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAccessApplications implements AccessApplicationInterface
type FakeAccessApplications struct {
	Fake *FakeCrdsV1alpha1
	ns   string
}

var accessapplicationsResource = schema.GroupVersionResource{Group: "crds.kubeflare.io", Version: "v1alpha1", Resource: "accessapplications"}

var accessapplicationsKind = schema.GroupVersionKind{Group: "crds.kubeflare.io", Version: "v1alpha1", Kind: "AccessApplication"}

// Get takes name of the accessApplication, and returns the corresponding accessApplication object, and an error if there is any.
func (c *FakeAccessApplications) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AccessApplication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(accessapplicationsResource, c.ns, name), &v1alpha1.AccessApplication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccessApplication), err
}

// List takes label and field selectors, and returns the list of AccessApplications that match those selectors.
func (c *FakeAccessApplications) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AccessApplicationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(accessapplicationsResource, accessapplicationsKind, c.ns, opts), &v1alpha1.AccessApplicationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AccessApplicationList{ListMeta: obj.(*v1alpha1.AccessApplicationList).ListMeta}
	for _, item := range obj.(*v1alpha1.AccessApplicationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested accessApplications.
func (c *FakeAccessApplications) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(accessapplicationsResource, c.ns, opts))

}

// Create takes the representation of a accessApplication and creates it.  Returns the server's representation of the accessApplication, and an error, if there is any.
func (c *FakeAccessApplications) Create(ctx context.Context, accessApplication *v1alpha1.AccessApplication, opts v1.CreateOptions) (result *v1alpha1.AccessApplication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(accessapplicationsResource, c.ns, accessApplication), &v1alpha1.AccessApplication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccessApplication), err
}

// Update takes the representation of a accessApplication and updates it. Returns the server's representation of the accessApplication, and an error, if there is any.
func (c *FakeAccessApplications) Update(ctx context.Context, accessApplication *v1alpha1.AccessApplication, opts v1.UpdateOptions) (result *v1alpha1.AccessApplication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(accessapplicationsResource, c.ns, accessApplication), &v1alpha1.AccessApplication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccessApplication), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAccessApplications) UpdateStatus(ctx context.Context, accessApplication *v1alpha1.AccessApplication, opts v1.UpdateOptions) (*v1alpha1.AccessApplication, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(accessapplicationsResource, "status", c.ns, accessApplication), &v1alpha1.AccessApplication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccessApplication), err
}

// Delete takes name of the accessApplication and deletes it. Returns an error if one occurs.
func (c *FakeAccessApplications) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(accessapplicationsResource, c.ns, name), &v1alpha1.AccessApplication{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAccessApplications) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(accessapplicationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AccessApplicationList{})
	return err
}

// Patch applies the patch and returns the patched accessApplication.
func (c *FakeAccessApplications) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AccessApplication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(accessapplicationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.AccessApplication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccessApplication), err
}
